# Generated by Django 4.2.1 on 2023-11-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_apartment_owner_pkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='room_option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Flat', 'Flat'), ('House', 'House'), ('Apartment', 'Apartment'), ('Villa', 'Villa')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bhk',
            field=models.CharField(default='1 BHK', max_length=10, null=True),
        ),
    ]
