# Generated by Django 4.2.1 on 2023-11-01 15:38

import Room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_apartment_deposit_apartment_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.png', null=True, upload_to=Room.models.upload_to_profile_pic),
        ),
    ]
