# Generated by Django 4.2.1 on 2023-11-01 18:43

import Room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='photo',
            field=models.ImageField(default='default_image.jpg', null=True, upload_to=Room.models.upload_to),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_1',
            field=models.ImageField(null=True, upload_to=Room.models.upload_to),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_2',
            field=models.ImageField(null=True, upload_to=Room.models.upload_to),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_3',
            field=models.ImageField(null=True, upload_to=Room.models.upload_to),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo_4',
            field=models.ImageField(null=True, upload_to=Room.models.upload_to),
        ),
    ]
